migrate:
	docker-compose run web rails db:migrate

rollback:
	docker-compose run web rails db:rollback

migratereset:
	docker-compose run web rails db:migrate:reset

seed:
	docker-compose run web rails db:seed

seedreset:
	docker-compose run web rails db:reset